### ISSUE TITLE
Charge Status

### ISSUE THREAD

**Issue by elchmartin** [cutiepi-io/cutiepi-shell#12]
I just got my CutiePi today - yay!

I plugged it in and let it sit for 2 hours or so, but when I unplug it, the battery drops from (only!) 55% to 5%....

It remains powered on but is this normal behaviour? 

What am I missing?

**Comment by penk** [comment]
@elchmartin hi, sounds like the charger isn't working. 

Some community members did mention that CutiePi is a little bit picky regarding charger or cable, that's why we've stated here to use regular 5V 3A power supply: 
https://github.com/cutiepi-io/cutiepi-doc#before-you-begin 

If you have other charger would you please try it out? Let us know if anything. 

Also, please upgrade to latest image, as it fixed battery voltage - percentage curve: 
https://github.com/cutiepi-io/pi-gen_stage4.5-cutiepi/releases/tag/2022-01-23

**Comment by elchmartin** [comment]
OK. First thing I learned is that I should not have started this ta night after working the whole day - should have figured out the get started guide.

I let the CutiePi charge during the night with a rather basic charger (~2A I think) and now it stated at 80% charge for some time, so I consider this fixed.

Will update the OS Image as the next step, maybe that will fix it completely.

Sorry for my impatience ;-)

**Comment by penk** [comment]
@elchmartin No problem, glad to learn that it works out for you. I'll close this issue for now. 
Feel free to reopen or create a new one when needed.
