### ISSUE TITLE
Many problems, Open Source?

### ISSUE THREAD

**Issue by rajiam** [cutiepi-io/cutiepi-shell#26]
1) CutiePi tablet Is not open source: I have been unable to boot up the CutiePi tablet with any other OS distro than the custom CutiePi OS distribution of Raspberry PI. I just get a backlit screen when I switch on the tablet. then nothing happens after that. How do I do this?
2) Arduino IDE will not properly install even using the terminal window. That is why I was trying to install another Raspberry Pi OS, so I could install and run Arduino IDE. How do I do this?
3) How do you use the camera? where is the camera app?
4) Will not discover bluetooth devices except my iPhone. Does not discover Bluetooth speakers or EarPods. How do I  fix this?

**Comment by penk** [comment]
@rajiam 

1. Please check your mail with the link I sent. I don't know what "other OS distro" is but you need at least configure the display overlay or panel driver. Using random OS will result in black screen and there's no way we can support. 
2. I don't know about specific application and I can't support that 
3. There's qcam camera app preinstalled on Raspberry Pi OS, and you can also use GStreamer pipeline for it. Please check documentation: https://www.raspberrypi.com/documentation/hardware/camera/ 
4. I don't know about specific product and I can't support that 

CutiePi is open source, and since we replied to many of your mail and message on Telegram, I'm going to close this issue.
